/*
# Seed Initial Data for Resonance Music Institute

## Purpose
Populate the database with initial courses, instructors, and other essential data.

## Data Included
- 6 Instructors with various specializations
- 12 Courses covering the full curriculum
- 6 Testimonials from students
- 8 Gallery images
- 6 Upcoming events
- 6 Blog posts
- 8 Shop products
*/

-- Instructors
INSERT INTO public.instructors (name, title, bio, specialization, image_url, email, phone, years_experience) VALUES
('Dr. Kwame Boateng', 'Director & Head of Piano Studies', 'With over 25 years of experience, Dr. Boateng has trained hundreds of professional pianists. He holds a Doctorate in Music from the University of Ghana.', ARRAY['Classical Piano', 'Worship Music', 'Music Theory'], 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 'kwame@resonance.edu.gh', '+233 53 848 0868', 25),
('Ama Asantewaa', 'Head of Vocal Training', 'A professional vocalist with experience performing internationally. Ama specializes in contemporary gospel and traditional African music.', ARRAY['Vocal Technique', 'Gospel Music', 'Performance'], 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 'ama@resonance.edu.gh', '+233 54 111 2222', 15),
('Kofi Mensah', 'Head of Guitar Studies', 'Kofi is a versatile guitarist proficient in classical, jazz, and contemporary styles. He has taught guitar for over 18 years.', ARRAY['Classical Guitar', 'Electric Guitar', 'Bass'], 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 'kofi@resonance.edu.gh', '+233 54 333 4444', 18),
('Nana Yaw Osei', 'Head of Percussion Studies', 'A master drummer who has performed with top African artists. Nana Yaw brings traditional and modern drumming techniques to his teaching.', ARRAY['Drum Set', 'Traditional Percussion', 'Rhythm Theory'], 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 'nana@resonance.edu.gh', '+233 54 555 6666', 20),
('Efua Darko', 'Head of Music Production', 'Efua is a certified audio engineer with experience in music production for film, television, and recording studios.', ARRAY['Music Production', 'Audio Engineering', 'Sound Design'], 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 'efua@resonance.edu.gh', '+233 54 777 8888', 12),
('Samuel Addo', 'Head of Worship Music', 'Samuel has served as music director for major churches across Ghana and brings practical worship ministry experience to his teaching.', ARRAY['Worship Leading', 'Church Music', 'Choir Direction'], 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 'samuel@resonance.edu.gh', '+233 54 999 0000', 16);

-- Courses
INSERT INTO public.courses (name, slug, description, full_description, duration_weeks, level, price, certificate_offered, image_url, instructor_id, featured, capacity, rating, features) VALUES
('Piano & Keyboard', 'piano-keyboard', 'Master the piano from basics to advanced performance. Learn classical, contemporary, and worship styles.', 'Our Piano & Keyboard program is designed to take you from complete beginner to confident performer. You will learn proper technique, music reading, chord progressions, and performance skills. The curriculum covers classical, contemporary, gospel, and worship music styles.', 24, 'beginner', 1500, true, 'https://images.pexels.com/photos/1246321/pexels-photo-1246321.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Dr. Kwame Boateng'), true, 20, 4.9, ARRAY['One-on-one lessons', 'Practice room access', 'Certificate upon completion', 'Recording opportunities', 'Performance workshops']),
('Guitar Mastery', 'guitar', 'From acoustic to electric, learn chords, scales, fingerpicking, and lead guitar techniques for various genres.', 'Whether you want to strum acoustic songs or shred on electric guitar, this comprehensive program covers it all. Learn chords, scales, music theory, fingerpicking, and lead techniques.', 20, 'intermediate', 1200, true, 'https://images.pexels.com/photos/1407354/pexels-photo-1407354.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Kofi Mensah'), true, 15, 4.8, ARRAY['Acoustic & Electric techniques', 'Group jam sessions', 'Performance training', 'Songwriting basics', 'Certificate upon completion']),
('Drum Performance', 'drums', 'Learn rhythm patterns, fills, and techniques for various genres including gospel, jazz, and contemporary music.', 'Drum Performance covers fundamental rhythm concepts, stick control, and coordination. Learn to play gospel, jazz, contemporary, and traditional African rhythms.', 16, 'beginner', 1000, true, 'https://images.pexels.com/photos/174630/pexels-photo-174630.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Nana Yaw Osei'), true, 12, 4.7, ARRAY['Professional drum kits', 'Practice pads provided', 'Play-along tracks', 'Band integration', 'Certificate upon completion']),
('Vocal Training', 'vocal', 'Develop your voice, breathing techniques, pitch accuracy, and performance confidence.', 'Our Vocal Training program helps you discover and develop your unique voice. Learn proper breathing, pitch control, vocal exercises, and performance techniques.', 12, 'beginner', 800, true, 'https://images.pexels.com/photos/167491/pexels-photo-167491.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Ama Asantewaa'), true, 25, 4.9, ARRAY['Breathing techniques', 'Vocal exercises', 'Song interpretation', 'Stage presence', 'Certificate upon completion']),
('Music Theory', 'music-theory', 'Understand the building blocks of music including scales, intervals, chords, and harmony.', 'Music Theory provides the foundation for all musical understanding. Learn to read and write music, understand chord progressions, and analyze musical compositions.', 12, 'beginner', 600, true, 'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Efua Darko'), false, 30, 4.6, ARRAY['Music notation', 'Harmony analysis', 'Ear training', 'Composition basics', 'Certificate upon completion']),
('Music Production', 'music-production', 'Learn to produce professional-quality music using industry-standard software and equipment.', 'Music Production teaches you to create, record, mix, and master music using professional digital audio workstations. Learn sound design, mixing techniques, and music business basics.', 20, 'intermediate', 2000, true, 'https://images.pexels.com/photos/1595385/pexels-photo-1595385.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Efua Darko'), true, 10, 4.8, ARRAY['DAW training', 'Mixing & Mastering', 'Sound design', 'Studio access', 'Certificate upon completion']),
('Bass Guitar', 'bass-guitar', 'Master the fundamentals of bass playing including technique, theory, and groove.', 'Bass Guitar program covers proper technique, finger style and pick playing, groove and timing, and music theory specifically for bassists.', 16, 'beginner', 1000, true, 'https://images.pexels.com/photos/169441/pexels-photo-169441.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Kofi Mensah'), false, 10, 4.7, ARRAY['Technique Mastery', 'Groove training', 'Theory application', 'Band workshops', 'Certificate upon completion']),
('Church Music', 'church-music', 'Specialized training for worship musicians including song leading, arrangement, and ministry.', 'Church Music program prepares you for music ministry. Learn worship leading, song arrangement, choir direction, and practical ministry skills.', 16, 'intermediate', 1200, true, 'https://images.pexels.com/photos/1199816/pexels-photo-1199816.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Samuel Addo'), false, 20, 4.9, ARRAY['Worship leading', 'Song arrangement', 'Choir direction', 'Ministry ethics', 'Certificate upon completion']),
('Ear Training', 'ear-training', 'Develop your ability to identify pitches, intervals, chords, and rhythms by ear.', 'Ear Training develops your musical hearing. Learn to identify intervals, chords, scales, and rhythms. Essential skill for all musicians.', 8, 'beginner', 500, true, 'https://images.pexels.com/photos/1644888/pexels-photo-1644888.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Dr. Kwame Boateng'), false, 40, 4.6, ARRAY['Interval recognition', 'Chord identification', 'Rhythm training', 'Dictation practice', 'Certificate upon completion']),
('Sight Reading', 'sight-reading', 'Learn to read and perform music at first sight with speed and accuracy.', 'Sight Reading teaches you to read and perform music notation fluently. Essential for session musicians and ensemble players.', 8, 'intermediate', 500, true, 'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Dr. Kwame Boateng'), false, 25, 4.5, ARRAY['Note reading', 'Rhythm reading', 'Key signatures', 'Practice materials', 'Certificate upon completion']),
('Song Writing', 'songwriting', 'Learn the art and craft of writing memorable songs including lyrics, melody, and structure.', 'Song Writing covers lyric composition, melody creation, song structure, and the creative process. Turn your ideas into complete songs.', 12, 'intermediate', 800, true, 'https://images.pexels.com/photos/1672735/pexels-photo-1672735.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Ama Asantewaa'), false, 15, 4.8, ARRAY['Lyric writing', 'Melody creation', 'Song structure', 'Copyright basics', 'Certificate upon completion']),
('Band Training', 'band-training', 'Learn to play effectively in a band setting, including communication, arrangement, and performance.', 'Band Training prepares you for real-world ensemble playing. Learn communication, arrangement, rehearsal techniques, and live performance.', 12, 'intermediate', 1000, true, 'https://images.pexels.com/photos/1672735/pexels-photo-1672735.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Nana Yaw Osei'), false, 12, 4.7, ARRAY['Ensemble playing', 'Communication', 'Arrangement', 'Live performance', 'Certificate upon completion']);

-- Testimonials
INSERT INTO public.testimonials (student_name, course, testimonial, rating, image_url, is_featured) VALUES
('Kwame Asante', 'Piano & Keyboard', 'Resonance Music Institute transformed my musical journey. The instructors are incredibly patient and skilled. I went from knowing nothing about piano to playing in my church within 6 months!', 5, 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=150&q=80', true),
('Ama Serwaa', 'Vocal Training', 'The vocal training program helped me discover my true voice. My confidence has skyrocketed, and I now lead worship at my church. Best decision I ever made!', 5, 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&q=80', true),
('Kofi Mensah', 'Guitar', 'I love the flexible class schedules and the small class sizes. My instructor took time to understand my goals and tailored the lessons accordingly. Highly recommend!', 5, 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150&q=80', true),
('Adwoa Agyeman', 'Music Production', 'The music production course opened up a whole new world for me. I have already produced songs for local artists and started my own studio business.', 4, 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&q=80', true),
('Yaw Osei', 'Drums', 'From complete beginner to playing in a band in 8 months! The drum program here is exceptional. The practice rooms are well-equipped too.', 5, 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&q=80', false),
('Efua Darko', 'Music Theory', 'I thought music theory would be boring, but the way it is taught here makes it so engaging. It has improved my overall musicianship tremendously.', 5, 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150&q=80', false);

-- Gallery Images
INSERT INTO public.gallery_images (title, category, image_url, description) VALUES
('Piano Masterclass Session', 'classroom', 'https://images.pexels.com/photos/1246321/pexels-photo-1246321.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'Students learning advanced piano techniques from Dr. Kwame Boateng.'),
('Sunday Worship Service', 'worship', 'https://images.pexels.com/photos/167491/pexels-photo-167491.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'Our students leading worship at a local church.'),
('Guitar Practice Room', 'classroom', 'https://images.pexels.com/photos/1407354/pexels-photo-1407354.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'One-on-one guitar lessons in our practice rooms.'),
('Annual Gospel Concert', 'concert', 'https://images.pexels.com/photos/1199816/pexels-photo-1199816.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'Students performing at our annual gospel concert at the National Theatre.'),
('Drum Workshop', 'workshop', 'https://images.pexels.com/photos/174630/pexels-photo-174630.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'Interactive drum workshop with Master Drummer Nana Yaw.'),
('Graduation Ceremony 2025', 'graduation', 'https://images.pexels.com/photos/267554/pexels-photo-267554.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'Celebrating our graduating class of 2025.'),
('Group Piano Session', 'classroom', 'https://images.pexels.com/photos/1644888/pexels-photo-1644888.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'Students practicing in our digital piano lab.'),
('Live Performance Night', 'performance', 'https://images.pexels.com/photos/1672735/pexels-photo-1672735.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'Students showcasing their talents at our monthly performance night.');

-- Events
INSERT INTO public.events (title, description, event_date, event_time, location, image_url, event_type, is_featured, max_attendees, registration_fee) VALUES
('Keyboard Masterclass', 'A special workshop with renowned pianist Dr. Kwame Boateng. Learn advanced techniques, improvisation, and performance tips.', '2026-07-15', '14:00', 'Main Auditorium, Resonance Campus', 'https://images.pexels.com/photos/1246321/pexels-photo-1246321.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'masterclass', true, 50, 150),
('Gospel Music Concert', 'Celebrate the spirit of gospel music with our talented students and special guest artists. A night of praise and worship.', '2026-07-22', '18:00', 'National Theatre, Accra', 'https://images.pexels.com/photos/1199816/pexels-photo-1199816.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'concert', true, 500, 100),
('Summer Graduation Ceremony', 'Celebrating the achievements of our graduating class. Join us for a memorable ceremony featuring student performances.', '2026-08-05', '10:00', 'Resonance Campus Auditorium', 'https://images.pexels.com/photos/267554/pexels-photo-267554.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'graduation', true, 200, 0),
('Guitar Workshop', 'Interactive session covering fingerpicking, solo techniques, and chord progressions. For intermediate players.', '2026-08-12', '15:00', 'Guitar Lab, Resonance Campus', 'https://images.pexels.com/photos/1407354/pexels-photo-1407354.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'workshop', false, 25, 120),
('Choir Auditions', 'Open auditions for our worship choir. Open to all skill levels. Preparation required.', '2026-09-02', '09:00', 'Choir Room, Resonance Campus', 'https://images.pexels.com/photos/1199816/pexels-photo-1199816.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'audition', false, 100, 0),
('Drum Clinic with Nana Yaw', 'Special drum clinic with Master Drummer Nana Yaw Osei. Learn traditional and contemporary drumming techniques.', '2026-09-15', '14:00', 'Drum Studio, Resonance Campus', 'https://images.pexels.com/photos/174630/pexels-photo-174630.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', 'masterclass', false, 30, 200);

-- Blog Posts
INSERT INTO public.blog_posts (title, slug, excerpt, content, category, tags, image_url, author_id, author_name, published, published_at, read_time) VALUES
('5 Essential Practice Techniques for Piano Beginners', 'piano-practice-techniques', 'Master the art of effective piano practice with these proven techniques that will accelerate your learning journey.', 'Learning to play the piano is a rewarding journey, but without proper practice techniques, progress can be slow and frustrating. Here are five essential practice techniques that every beginner should know...', 'Piano Tips', ARRAY['piano', 'practice', 'beginners', 'techniques'], 'https://images.pexels.com/photos/1246321/pexels-photo-1246321.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Dr. Kwame Boateng'), 'Dr. Kwame Boateng', true, '2026-06-20', '5 min read'),
('Finding Your Unique Voice in Gospel Music', 'gospel-music-voice', 'Learn how to develop your distinctive sound and style in gospel music while staying true to the tradition.', 'Gospel music has a rich heritage that spans generations. As a musician, finding your unique voice within this tradition requires both respect for the past and creative innovation...', 'Worship Music', ARRAY['gospel', 'worship', 'voice', 'style'], 'https://images.pexels.com/photos/167491/pexels-photo-167491.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Samuel Addo'), 'Samuel Addo', true, '2026-06-15', '7 min read'),
('Understanding Music Theory: A Beginner''s Guide', 'music-theory-guide', 'Demystify music theory with this comprehensive guide designed for complete beginners.', 'Music theory often seems intimidating, but it doesnt have to be. At its core, music theory is simply the language we use to describe and understand music...', 'Music Theory', ARRAY['theory', 'beginners', 'fundamentals', 'scales'], 'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Efua Darko'), 'Efua Darko', true, '2026-06-10', '10 min read'),
('From Student to Studio: A Graduate''s Success Story', 'student-success-story', 'Read how Kwame Asante transformed his passion for music into a flourishing career after graduating from Resonance.', 'When Kwame Asante enrolled at Resonance Music Institute in 2018, he had no idea his journey would lead to opening his own recording studio...', 'Success Stories', ARRAY['success', 'graduates', 'inspiration', 'career'], 'https://images.pexels.com/photos/1595385/pexels-photo-1595385.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', NULL, 'Editorial Team', true, '2026-06-05', '6 min read'),
('Drumming for Worship: Rhythm in Gospel Services', 'drumming-worship', 'Discover the role of drums in modern gospel services and how to play with sensitivity and power.', 'Drums in worship music require a unique approach. Unlike secular performances, worship drumming is about serving the congregation and enhancing the spiritual atmosphere...', 'Drums', ARRAY['drums', 'worship', 'rhythm', 'gospel'], 'https://images.pexels.com/photos/174630/pexels-photo-174630.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Nana Yaw Osei'), 'Nana Yaw Osei', true, '2026-05-28', '8 min read'),
('The Art of Live Performance: Tips from the Stage', 'live-performance-tips', 'Get expert advice on overcoming stage fright and delivering memorable live performances.', 'Performing live is one of the most rewarding aspects of being a musician. However, even seasoned performers can struggle with stage fright...', 'Performance', ARRAY['performance', 'stage', 'confidence', 'tips'], 'https://images.pexels.com/photos/1672735/pexels-photo-1672735.jpeg?auto=compress&cs=tinysrgb&w=800&q=80', (SELECT id FROM public.instructors WHERE name = 'Ama Asantewaa'), 'Ama Asantewaa', true, '2026-05-20', '6 min read');

-- Products
INSERT INTO public.products (name, slug, description, price, category, image_url, stock, is_digital, rating, reviews) VALUES
('Keyboard Unlocked: Complete Guide', 'keyboard-unlocked', 'A comprehensive guide for learning keyboard from beginner to advanced. Includes video lessons access.', 89, 'book', 'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 50, true, 4.8, 45),
('Music Theory Made Easy', 'music-theory-easy', 'Simple approach to understanding music theory. Perfect for beginners.', 69, 'book', 'https://images.pexels.com/photos/1644888/pexels-photo-1644888.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 35, true, 4.9, 32),
('M-Audio Keystation 88 Key', 'm-audio-keystation', 'Professional 88-key MIDI controller keyboard with semi-weighted keys.', 1250, 'instrument', 'https://images.pexels.com/photos/1246321/pexels-photo-1246321.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 8, false, 4.7, 18),
('Sustain Pedal Pro', 'sustain-pedal', 'Professional piano-style sustain pedal compatible with most keyboards and digital pianos.', 79, 'accessory', 'https://images.pexels.com/photos/1246321/pexels-photo-1246321.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 25, false, 4.5, 12),
('Resonance Branded T-Shirt', 'resonance-tshirt', 'Premium quality cotton t-shirt with the Resonance logo. Available in multiple sizes.', 59, 'apparel', 'https://images.pexels.com/photos/996321/pexels-photo-996321.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 100, false, 4.6, 24),
('Practice Notebook', 'practice-notebook', 'Dedicated notebook for tracking your practice sessions and musical progress.', 25, 'material', 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 80, false, 4.4, 8),
('Beginner Guitar Pack', 'beginner-guitar', 'Acoustic guitar starter pack with gig bag, pick, and spare strings.', 450, 'instrument', 'https://images.pexels.com/photos/1407354/pexels-photo-1407354.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 12, false, 4.7, 22),
('Digital Metronome', 'digital-metronome', 'Digital metronome with multiple time signatures and tempo ranges.', 49, 'accessory', 'https://images.pexels.com/photos/1644888/pexels-photo-1644888.jpeg?auto=compress&cs=tinysrgb&w=400&q=80', 45, false, 4.8, 15);
